### ISSUE TITLE
Automated dependency update results in duplicate entries.

### ISSUE THREAD

**Issue by ben51degrees** [51Degrees/device-detection-dotnet-examples#229]
See [Framework-Web.csproj](https://github.com/51Degrees/device-detection-dotnet-examples/blob/a1efa5d2dcc9121177b4c331d3ffc4e8159125f5/Examples/OnPremise/Framework-Web/Framework-Web.csproj#L125).
Each time the update packages workflow runs, it adds another entry into the csproj file, instead of replacing the existing one. Does not seem to break the build, but could be cleaned up.

**Comment by justadreamer** [comment]
@pi-alexander-popel could you please take a look at this one
