### ISSUE TITLE
Running Hash Performance Example Fails

### ISSUE THREAD

**Issue by ben51degrees** [51Degrees/device-detection-dotnet-examples#232]
When running the Hash performance example using the latest YML evidence file, and Enterprise Hash file, a `NullReferenceException` is thrown from the `ProcessMethod` on [line 184](https://github.com/51Degrees/device-detection-dotnet-examples/blob/main/Examples/OnPremise/Performance-Console/Program.cs#L184).

Using the Lite data file, and 20000 evidence file works fine. So the issue is likely in the larger test evidence file (or the reading of).

The exception gives no more information than that, so catching and logging the evidence that's been passed in would be a good start to finding the issue.

**Comment by jwrosewell** [comment]
I suspect this is due to bad header data in the evidence file that is not present in the small 20,000 file. The code needs to be tested to handle an invalid header, perhaps missing one of the evidence prefixes.

**Comment by justadreamer** [comment]
@drasmart let's retest this one with the 1M records YAML file and see if the issue still exists. (will provide the file)

**Comment by justadreamer** [comment]
@drasmart can you please comment with what you sent on Slack, thanks.

**Comment by justadreamer** [comment]
@drasmart could you please check if null and ~ values in YAML interpreted as null in native code is per YAML specification?  or is it the bug of our Yaml parser, or is it a convention.  if it is just interpretation problem - can we replace it with just a string "null" or "~" in the export.

**Comment by justadreamer** [comment]
Here are the failures in builds due to this exception thrown:

- https://github.com/51Degrees/device-detection-dotnet-examples/actions/runs/9441489543/job/26002296207#step:5:663
- https://github.com/51Degrees/device-detection-dotnet/actions/runs/9441633634/job/26003212611#step:6:2015

Let's not throw that exception and rather issue a warning and skip such evidence to make the builds pass

**Comment by justadreamer** [comment]
Hi @ben51degrees this has been addressed as part of the ExampleBase, could you please check, thanks.
