### ISSUE TITLE
Issues Setting-up Web & Apple Examples

### ISSUE THREAD

**Issue by Jamesr51d** [51Degrees/device-detection-dotnet-examples#234]
# Set-Up 
I cloned the repo and updated the submodules. Below are issues I faced when initially running the Apple and Web related examples.

# Issues List
- [x] Example: GettingStarted-Web-ClientOnly. Issue: GET request fails with a 404 when trying to retrieve "https://cloud.51degrees.com/api/v4/.js". This may be preventing results from being returned.
- [x] AppleServerSide(Config) Project in on-premise is not documented as part of the example list in the README
- [x] AppleServersideConfig Project doesnt include instructions as to which/where to get the relevant Apple file ("Macintosh.data.json"). It is not clear in documentation that the default datafile is not the Lite file as Apple detection requires a Paid subscription / paid file.

# Objective 

- Clear up the documentation to better explain the Apple Projects and requirements. 
- Investigate and rectify the cause of the 404 error to the cloud service.

**Comment by justadreamer** [comment]
@drasmart could you please take a look at the first point - is it just a matter of providing a RESOURCE_KEY somewhere in the config?

**Comment by Jamesr51d** [comment]
Yeah, RESOURCE_KEY needed setting. This issue can be closed.
